### ISSUE TITLE
Unable to open textgrid files

### ISSUE THREAD

**Issue by fusaroli** [tjmahr/textgrid#6]
Trying to open any of my text grid files (e.g. https://www.dropbox.com/s/szf5ynhlwhz2er4/LM_BTT_37_Mother.TextGrid?dl=0) 

I get the following:

> error in mapply(FUN = f, ..., SIMPLIFY = FALSE) : 
>   zero-length inputs cannot be mixed with those of non-zero length

**Comment by tjmahr** [comment]
I've been using textgRid by @patrickreidy for my textgrid needs. this package (mine) was a fork of that one (pat's). https://github.com/patrickreidy/textgRid It's on CRAN and has the same API, so I recommend it. (I should probably take this package offline...)

ANYWAY, both of our packages have this problem. My fix has been to temporarily fix the file before reading it in. 

``` r


u <- "~/../Downloads/LM_BTT_37_Mother.TextGrid"

temp_fix_textgrid <- function(x) {
  temp <- tempfile(fileext = ".TextGrid")
  
  lines <- readr::read_lines(x)
  lines <- stringr::str_replace_all(lines, "\t{4}", "\t\t\t")
  lines <- stringr::str_replace_all(lines, "\t", "    ")
  readr::write_lines(lines, temp)
  temp
}

textgRid::TextGrid(u)
#> Error in mapply(FUN = f, ..., SIMPLIFY = FALSE): zero-length inputs cannot be mixed with those of non-zero length
textgRid::TextGrid(temp_fix_textgrid(u))
#> An object of class "TextGrid"
#> [[1]]
#> An object of class "IntervalTier"
#> Slot "startTimes":
#> [1] 0.000 0.013 0.122 0.383 0.552 0.722 0.752 0.882
#> 
#> Slot "endTimes":
#> [1] 0.013 0.122 0.383 0.552 0.722 0.752 0.882 0.889
#> 
#> Slot "labels":
#> [1] "sp"    "sp"    "s"     "Â¹ÊŒ"  "d"     "â\201°Ã¦" "n"     "sp"   
#> 
#> Slot "name":
#> [1] "default - phone"
#> 
#> Slot "number":
#> [1] 1
#> 
#> 
#> [[2]]
#> An object of class "IntervalTier"
#> Slot "startTimes":
#> [1] 0.000 0.013 0.122 0.882
#> 
#> Slot "endTimes":
#> [1] 0.013 0.122 0.882 0.889
#> 
#> Slot "labels":
#> [1] "sp"     "sp"     "SÃ…DAN" "sp"    
#> 
#> Slot "name":
#> [1] "default - word"
#> 
#> Slot "number":
#> [1] 2
#> 
#> 
#> Slot "startTime":
#> [1] 0
#> 
#> Slot "endTime":
#> [1] 0.889
```

<sup>Created on 2019-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by fusaroli** [comment]
Thanks! I had seen the other, but I thought I'd trust yours. I bypassed the issue by using rPraat for importing the data.
